### ISSUE TITLE
Use /dev/serial/by-id instead of /dev/serial/by-path/ for SKR1.3 setup guide (and any other)

### ISSUE THREAD

**Issue by gchedzhemov** [VoronDesign/VoronUsers#173]
@jdlongenecker, I would suggest updating `ls -l /dev/serial/by-path/` instructions to be `ls -l /dev/serial/by-id` in order to avoid issues with controllers being swapped on USB ports later in the build or during troubleshooting

E.g, instead of 
```
pi@octovoron:~ $ ls -l /dev/serial/by-path/platform-fd500000.pcie-pci-0000\:01\:00.0-usb-0\:1.3\:1.0
lrwxrwxrwx 1 root root 13 Oct 13 08:50 /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0 -> ../../ttyACM0
pi@octovoron:~ $ ls -l /dev/serial/by-path/platform-fd500000.pcie-pci-0000\:01\:00.0-usb-0\:1.4\:1.0
lrwxrwxrwx 1 root root 13 Oct 13 08:50 /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0 -> ../../ttyACM1
```

```
pi@octovoron:~ $ ls -l /dev/serial/by-id/usb-Klipper_lpc1768_02900009881C4AAFA085685DC02000F5-if00
lrwxrwxrwx 1 root root 13 Oct 13 08:50 /dev/serial/by-id/usb-Klipper_lpc1768_02900009881C4AAFA085685DC02000F5-if00 -> ../../ttyACM0
pi@octovoron:~ $ ls -l /dev/serial/by-id/usb-Klipper_lpc1768_0800011348104AAFD9B8675DC22000F5-if00
lrwxrwxrwx 1 root root 13 Oct 13 08:50 /dev/serial/by-id/usb-Klipper_lpc1768_0800011348104AAFD9B8675DC22000F5-if00 -> ../../ttyACM1
```

Happy to make the edits for you if given access to source doc.

**Comment by FHeilmann** [comment]
In order to streamline our docs we have moved most documentation to VoronDesign/Voron-Documentation repository, which will soon be turned into a whole website just for documentation. 

As you can probably see by now (or later today) the guide you're referencing has been removed from this repo, that's why I'm closing this issue for now.

Feel free to check the docs once they are available and report this issue if it carries over to that site.

-Florian
