### ISSUE TITLE
Volcano version, would it be possible?

### ISSUE THREAD

**Issue by Rodrigormaraujo** [VoronDesign/VoronUsers#505]
Is there any chance of having a version for e3d volcano? Thanks.

**Comment by FHeilmann** [comment]
Official Voron toolheads won't support the Volcano. Since you haven't mentioned any mod in particular I'd assume you're in the wrong place. This repository is meant for community submitted mods. If you want to commission a mod, you're better off asking on our discord or reddit whether someone will design a toolhead for you.
